<?php
  // This file is generated by Composer
  require_once 'vendor/autoload.php';

  $client = new \Imgur\Client();
  $client->setOption('client_id', '0910235d51f0f8e');
  $client->setOption('client_secret', 'd8b71f04952f23b23a805f8f14a79cb6e7c92912');

  if (isset($_SESSION['token'])) {
    $client->setAccessToken($_SESSION['token']);
    if($client->checkAccessTokenExpired()) {
      $client->refreshToken();
    }
  }
  elseif (isset($_GET['code'])) {
      $client->requestAccessToken($_GET['code']);
      $_SESSION['token'] = $client->getAccessToken();
  }
  else {
  }

  $images = $client->api('gallery')->randomGalleryImages();
  $imageNumber = rand(0, 40);
  // If strength length of $images[$imageNumber]->getLink() is short, get a new image number

  $link = $images[$imageNumber]->getLink();
  $title = $images[$imageNumber]->getTitle();
?>
<!DOCTYPE html>
<html>
<head>
  <title><?php echo $title ?></title>
  <meta charset="UTF-8">
  <meta name="description" content="Random images pulled from the Imgur API">
  <meta name="keywords" content="Funny, image, random, randomized">
  <meta name="author" content="Sean Perryman">
  <style>
    .image {
      max-width: 100%;
      max-height: 100%;
      bottom: 0;
      left: 0;
      margin: auto;
      overflow: auto;
      position: fixed;
      right: 0;
      top: 0;
    }
    html { 
      background-color: black; 
    }
    p, a { display: none; }
    h1 {
      color: rgb(25,25,25);
      text-align: center;
      margin-top: 30%;
    }
  </style>
  <script>
    function reloadPage() {
      window.location.href = window.location.href
    }

    window.onclick = reloadPage;
  </script>
  
</head>
<body>
  
  <p><?php echo $title ?></p>
  <img class="image" src='<?php echo $link; ?>'>
  <h1>Click to refresh!</h1>
  <p>My other sites, for those of you reading the HTML source</p>
  <p>I bought this domain name a while back and never had the gumption to do something with it, so this is what came of it finally.
     I find myself sitting here and just clicking through images for long periods of time, I hope that it brings you joy as well.</p>
  <a href="http://seanperryman.com">Sean Perryman.com</a>
  <a href="http://bakersfieldbrew.com">Bakersfield Brew</a>
  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58643956-1', 'auto');
    ga('send', 'pageview');

  </script>
</body>
</html>